version: '3'
services:
  mdw:
    hostname: mdw
    image: "mygreenplum"
    ports:
     - "5222:22"
     - "5432:5432"
  sdw1:
    hostname: sdw1
    image: "mygreenplum"
  amdw:
    hostname: amdw
    image: "mygreenplum"
  asdw1:
    hostname: asdw1
    image: "mygreenplum"
